### ISSUE TITLE
Unexpected token - preact-rollup-redux

### ISSUE THREAD

**Issue by katopz** [fdaciuk/preact-react-redux-playground#9]
For some reason I got...
```
$ rollup -c
/Users/katopz/git/preact-react-redux-playground/preact-rollup-redux/src/main.js: Unexpected token (6:7)
SyntaxError: /Users/katopz/git/preact-react-redux-playground/preact-rollup-redux/src/main.js: Unexpected token (6:7)
  4 | import App from './components/app'
  5 | 
> 6 | render(<App />, document.querySelector('[data-js="main"]'))
    | 
```
Any hint? Thanks

**Comment by fdaciuk** [comment]
@katopz Good catch! 

You must pass `BABEL_ENV=production` before to run this command =)

I fix the `package.json` so, you can run: `npm run build` :)

**Comment by katopz** [comment]
Hi @fdaciuk 

I test on Windows seem to need more step tho, I will log it here in case someone get stuck.
For  Windows CMD, you will need to run this one by one...
```
SET BABEL_ENV=production
SET UGLIFY=true
rollup -c
```
I try to warp it as one line via `package.json` but no luck.
Anyway it doesn't matter, I just say it out loud and it should be fine on OSX ;)

Thanks!

**Comment by katopz** [comment]
And to eliminate this via console log
```
You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.
```
I need to add
```
NODE_ENV=production
```
This should save someone time (yes I'm noob! everybody seem to know this but I'm not, lol)

Cheers!

**Comment by fdaciuk** [comment]
Thanks for this tips @katopz! I use Linux, so, I would never have known it xD

I will add this steps on README =)

**Comment by fdaciuk** [comment]
@katopz: done! :dancer: :dancer: :sparkles: 

https://github.com/fdaciuk/preact-react-redux-playground/tree/master/preact-rollup-redux

**Comment by katopz** [comment]
@fdaciuk awesome! :trophy:
